name: Lint and format
on: push
env:
  SRC_FILES: '*.py'
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - name: Install ruff
        run: pip3 install ruff
      - name: Check lint and format
        run: python3 -m ruff check $SRC_FILES
